version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100
