version: 0.2

phases:
  build:
      commands:
      - echo "This is build phase... zipping my webpage"
      
  post_build:
    commands:
    - echo "Deployed to S3"
artifacts:
  files:
     - appspec.yml
    - target/SampleMavenTomcatApp.war
    - scripts/*


